version: '3.5'
services:
  petclinic-server:
    container_name: petclinic-server
    image: bryandollery/petclinic-server
    build: ./petclinic-server
    ports:
      - "8080:9966"
    depends_on:
      - petclinic-db
  petclinic-client:
    container_name: petclinic-client
    image: bryandollery/petclinic-client
    build: ./petclinic-client
    ports: 
      - "8081:8400"
  petclinic-db:
    container_name: petclinic-db
    image: bryandollery/petclinic-db
    build: ./petclinic-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_DB=petclinic
    volumes:
      - petclinic-db:/var/lib/postgresql/data

volumes:
    petclinic-db:
        name: petclinic-db
