version: '3.5'
services:
  petclinic-server:
    container_name: petclinic-server
    image: bryandollery/petclinic-server
    build: ./petclinic-server
    ports:
      - "8080:9966"
    restart: always
    depends_on:
      - db
  petclinic-client:
    container_name: petclinic-client
    image: bryandollery/petclinic-client
    build: ./petclinic-client
    ports: 
      - "8081:8400"
    restart: always
  db:
    container_name: db
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: petclinic
      POSTGRES_PASSWORD: petclinic
      POSTGRES_USER: postgres

volumes:
    db-data:
